version: "3"
services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    volumes:
      - /var/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
