version: "3"
services:
  saasbase:
    image: ghost:4.27.1
    ports:
      - "3009:2368"
    environment:
      - url="https://saasbase.dev"
      - mail__transport="SMTP"
      - mail__options__service="Mailgun"
      - mail__options__auth__user="postmaster@saasbase.dev"
      - mail__options__auth__pass=${MAILGUN_API_KEY}
    volumes:
      - /var/saasbase:/var/lib/ghost/content
